# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/andoi/Documents/Unibersidad/PBL/Serial/TOP_DIBINA150121/TOP_DIBINA/TOP_DIBINA.cache/wt [current_project]
set_property parent.project_path C:/Users/andoi/Documents/Unibersidad/PBL/Serial/TOP_DIBINA150121/TOP_DIBINA/TOP_DIBINA.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/andoi/Documents/Unibersidad/PBL/Serial/TOP_DIBINA150121/TOP_DIBINA/TOP_DIBINA.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/andoi/Documents/Unibersidad/PBL/Serial/TOP_DIBINA150121/TOP_DIBINA/TOP_DIBINA.srcs/sources_1/imports/COMPONENTES/me_display/FSM.vhd
  C:/Users/andoi/Documents/Unibersidad/PBL/Serial/TOP_DIBINA150121/TOP_DIBINA/TOP_DIBINA.srcs/sources_1/imports/COMPONENTES/me_display/ME_display.vhd
  C:/Users/andoi/Documents/Unibersidad/PBL/Serial/TOP_DIBINA150121/TOP_DIBINA/TOP_DIBINA.srcs/sources_1/imports/COMPONENTES/TOP_Principal.vhd
  C:/Users/andoi/Documents/Unibersidad/PBL/Serial/TOP_DIBINA150121/TOP_DIBINA/TOP_DIBINA.srcs/sources_1/imports/COMPONENTES/convertidor/abecedario.vhd
  C:/Users/andoi/Documents/Unibersidad/PBL/Serial/TOP_DIBINA150121/TOP_DIBINA/TOP_DIBINA.srcs/sources_1/imports/COMPONENTES/linea_serie_vhd/baud.vhd
  C:/Users/andoi/Documents/Unibersidad/PBL/Serial/TOP_DIBINA150121/TOP_DIBINA/TOP_DIBINA.srcs/sources_1/imports/COMPONENTES/convertidor/bin_decimal.vhd
  C:/Users/andoi/Documents/Unibersidad/PBL/Serial/TOP_DIBINA150121/TOP_DIBINA/TOP_DIBINA.srcs/sources_1/imports/COMPONENTES/convertidor/cantidad_display.vhd
  C:/Users/andoi/Documents/Unibersidad/PBL/Serial/TOP_DIBINA150121/TOP_DIBINA/TOP_DIBINA.srcs/sources_1/imports/COMPONENTES/me_display/f_zati.vhd
  C:/Users/andoi/Documents/Unibersidad/PBL/Serial/TOP_DIBINA150121/TOP_DIBINA/TOP_DIBINA.srcs/sources_1/imports/COMPONENTES/linea_serie_vhd/kcuart_rx.vhd
  C:/Users/andoi/Documents/Unibersidad/PBL/Serial/TOP_DIBINA150121/TOP_DIBINA/TOP_DIBINA.srcs/sources_1/imports/COMPONENTES/linea_serie_vhd/kcuart_tx.vhd
  C:/Users/andoi/Documents/Unibersidad/PBL/Serial/TOP_DIBINA150121/TOP_DIBINA/TOP_DIBINA.srcs/sources_1/imports/COMPONENTES/convertidor/mux.vhd
  C:/Users/andoi/Documents/Unibersidad/PBL/Serial/TOP_DIBINA150121/TOP_DIBINA/TOP_DIBINA.srcs/sources_1/imports/COMPONENTES/linea_serie_vhd/serial_rx.vhd
  C:/Users/andoi/Documents/Unibersidad/PBL/Serial/TOP_DIBINA150121/TOP_DIBINA/TOP_DIBINA.srcs/sources_1/imports/COMPONENTES/linea_serie_vhd/serial_tx.vhd
  C:/Users/andoi/Documents/Unibersidad/PBL/Serial/TOP_DIBINA150121/TOP_DIBINA/TOP_DIBINA.srcs/sources_1/imports/COMPONENTES/convertidor/top_convertidor.vhd
  C:/Users/andoi/Documents/Unibersidad/PBL/Serial/TOP_DIBINA150121/TOP_DIBINA/TOP_DIBINA.srcs/sources_1/imports/linea_serie_vhd/top_serial.vhd
  C:/Users/andoi/Documents/Unibersidad/PBL/Serial/TOP_DIBINA150121/TOP_DIBINA/TOP_DIBINA.srcs/sources_1/imports/COMPONENTES/convertidor/traductor_empresa.vhd
  C:/Users/andoi/Documents/Unibersidad/PBL/Serial/TOP_DIBINA150121/TOP_DIBINA/TOP_DIBINA.srcs/sources_1/imports/COMPONENTES/convertidor/traductor_producto.vhd
  C:/Users/andoi/Documents/Unibersidad/PBL/Serial/TOP_DIBINA150121/TOP_DIBINA/TOP_DIBINA.srcs/sources_1/new/TOP_DIBINA.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/andoi/Documents/Unibersidad/PBL/Serial/TOP_DIBINA150121/TOP_DIBINA/TOP_DIBINA.srcs/constrs_1/imports/SLP_Vivado/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/andoi/Documents/Unibersidad/PBL/Serial/TOP_DIBINA150121/TOP_DIBINA/TOP_DIBINA.srcs/constrs_1/imports/SLP_Vivado/Basys3_Master.xdc]


synth_design -top TOP_DIBINA -part xc7a35tcpg236-1


write_checkpoint -force -noxdef TOP_DIBINA.dcp

catch { report_utilization -file TOP_DIBINA_utilization_synth.rpt -pb TOP_DIBINA_utilization_synth.pb }
